# Add reusable labels in your docker-compose.yml file(s) like this:
x-traefik-common:
  labels: &x-traefik-common-labels
    traefik.enable: true
    traefik.http.middlewares.append-first-level-trailing-slash.replacepathregex.regex: '^/([a-z]+)$'
    traefik.http.middlewares.append-first-level-trailing-slash.replacepathregex.replacement: '/$1/'

# Use by adding the following to your service:
# labels:
#   <<: *x-traefik-common-labels
#   traefik.http.routers.[name].middlewares: append-first-level-trailing-slash
#   traefik.http.routers.[name].rule: Host(`[host]`) && PathPrefix(`/[path]`)"

services:
  traefik:
    container_name: traefik
    image: traefik:v3.6
    restart: unless-stopped
    command:
      #- "--log.level=DEBUG"
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"
      
      # Entrypoints
      - "--entrypoints.web.address=:3000"
      - "--entrypoints.websecure.address=:3443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.traefik.address=:9000"
      
      # Global Redirection (HTTP -> HTTPS)
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      # API
      - "--api.insecure=true"

      # Providers
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.defaultRule=Host(`{{ .ContainerName }}.localhost`)"
      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"
      
      # Logs
      - "--accesslog=true"
      - "--accesslog.fields.names.StartUTC=drop"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic:/dynamic:ro
      - ./certs:/certs:ro
    
    ports:
      - "80:3000"  # Redirects to https://localhost:3443
      - "3000:3000"
      - "443:3443"  # Redirects to http://localhost:3000
      - "3443:3443"
      - "9000:9000"
    
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

    labels:
      traefik.enable: "true"

    environment:
      - TZ=${TZ:-Europe/Stockholm}

networks:
  default:
    name: traefik
